### ISSUE TITLE
Error when enabling interface = mouse

### ISSUE THREAD

**Issue by TopDown71** [helgeerbe/picframe#307]

**Comment by TopDown71** [comment]
When enabling interface = mouse I encounter the following when picframe starts up. It looks like the absolute path is an unusual concatenation of path strings due to my having changed the default user name for the PI. The yaml file comment is also unclear about entering the characters as mouse or "mouse" since the default null has no quotes. The result seems to be the same either way.

picframe ~/picframe_data/config/configuration.yaml
INFO:start.py:starting ['/home/Dan/.local/bin/picframe', '/home/Dan/picframe_data/config/configuration.yaml']
INFO:model.Model:Open config file: /home/Dan/picframe_data/config/configuration.yaml:
Traceback (most recent call last):
  File "/home/Dan/.local/lib/python3.7/site-packages/pi3d/util/Font.py", line 113, in __init__
    imgfont = ImageFont.truetype(font, font_size)
  File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFont.py", line 976, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFont.py", line 973, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFont.py", line 250, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Dan/.local/bin/picframe", line 8, in <module>
    sys.exit(main())
  File "/home/Dan/.local/lib/python3.7/site-packages/picframe/start.py", line 135, in main
    c.start()
  File "/home/Dan/.local/lib/python3.7/site-packages/picframe/controller.py", line 331, in start
    self.__interface_peripherals = InterfacePeripherals(self.__model, self.__viewer, self)
  File "/home/Dan/.local/lib/python3.7/site-packages/picframe/interface_peripherals.py", line 53, in __init__
    self.__gui = self.__get_gui()
  File "/home/Dan/.local/lib/python3.7/site-packages/picframe/interface_peripherals.py", line 132, in __get_gui
    spacing=0,
  File "/home/Dan/.local/lib/python3.7/site-packages/pi3d/util/Font.py", line 120, in __init__
    raise Exception(msg)
Exception: Couldn't find font file '~/picframe_data/data/fonts/NotoSans-Regular.ttf' - absolute path is '/home/Dan/~/picframe_data/data/fonts/NotoSans-Regular.ttf'

**Comment by TopDown71** [comment]
When I pasted the last text the strikeout formatting was applied and changed "/home/Dan/tilde/picfram..." to /home/Dan//picfram..."

**Comment by jgodfrey** [comment]
@TopDown71 - I just edited the original post to add `code` blocks around the traces. Hope that's OK...

**Comment by TopDown71** [comment]
This issue 'may' have been caused by several modifications affecting text size, matting, and borders in the yaml file. There were no issues until I enabled the mouse support. I will evaluate each change separately to see if I can reproduce this.

**Comment by helgeerbe** [comment]
OK, will close it now.
