### ISSUE TITLE
Filtering via Home Assistant stopped working

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#388]
This one is for the master of Home Assistant, @helgeerbe ! :-)

I have always loved the filter possibilities of Pi3D via Home Assistant. However, some time ago, it stopped working. So, it has no effect if I now enter a keyword or modify the dates. HA is updated all the time, so I guess something broke along the way.

Was there anything that needed to be changed? I still use your old blueprint, which worked wonderfully before it didn't.

**Comment by sapnho** [comment]
![Screenshot_2024-05-30_at_10_42_54](https://github.com/helgeerbe/picframe/assets/33040431/87cb04a4-4417-4a51-a40a-12fca1c16df1)

**Comment by sapnho** [comment]
![Screenshot 2024-05-30 at 10 44 13](https://github.com/helgeerbe/picframe/assets/33040431/30b11653-4833-4128-8ce5-b6137e057118)

**Comment by helgeerbe** [comment]
Hi Wolfgang,

I can confirm that this stopped working. I don't know why yet. But I hope I have time this weekend to fix it.

**Comment by sapnho** [comment]
Ah, good to know! Thanks!

**Comment by helgeerbe** [comment]
Home Assistant changed the way how it handles text sensors. Sensor devices are now limited to numbers. Text sensors have to use now the new text device entity.

I fixed this and created a new blueprint. This works as expected on my own devices. 

Will deploy a new versions of picframe and the home assistant blueprint this weekend.

**Comment by sapnho** [comment]
Oh, wow, great. Many thanks!

**Comment by sapnho** [comment]
@helgeerbe I just did a fresh install on a Pi 4 with Buster. The max version of picframe I get to is 2023.07.26.post1

During installation, I got the following text:

> Collecting picframe
  Downloading picframe-2024.5.31-py3-none-any.whl.metadata (3.9 kB)
INFO: pip is looking at multiple versions of picframe to determine which version is compatible with other requirements. This could take a while.
  Downloading https://www.piwheels.org/simple/picframe/picframe-2024.2.19-py3-none-any.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 3.0 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/picframe/picframe-2023.7.26.post1-py3-none-any.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 2.9 MB/s eta 0:00:00

So, could it be that I can't use your latest commit with Buster?

**Comment by sapnho** [comment]
Which OS version are you using?

**Comment by helgeerbe** [comment]
I use bullseye. 
````cmd
pi@picframe:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
````

Is there a reason why you try buster?

**Comment by sapnho** [comment]
I remember there was one issue with Bullseye back then which kept me using Buster. I'll do a fresh install with Buster and will check. Would you have the Bullseye specific instructions somewhere?

**Comment by helgeerbe** [comment]
What happens if you try `pip install picframe==2024.5.31`

**Comment by sapnho** [comment]
I am in the middle of installing Bullseye.. :-)

What I would need are the raspi config settings and the manual start command line..

**Comment by sapnho** [comment]
I am also having troubles with all the commands for Buster that I documented here: https://www.thedigitalpictureframe.com/how-to-add-crossfading-slide-transitions-to-your-digital-picture-frame-using-pi3d/

Do we have a Bullseye installation wiki somewhere?

**Comment by helgeerbe** [comment]
This ist still my fastest approach: https://gist.github.com/thomasedoff/3973846101da1e7496524be075f1c02f
And the best, ist doesn't require to run something with sudo as root.

**Comment by sapnho** [comment]
Even this
`python3 -m pip install picframe
doesn't work.`

> /usr/bin/python3: No module named pip

**Comment by helgeerbe** [comment]
`sudo apt install python3-pip`

**Comment by sapnho** [comment]
Thanks. That solves one thing but `picframe -i .
 ` results in

`Traceback (most recent call last):
  File "/home/pi/.local/bin/picframe", line 5, in <module>
    from picframe.start import main
  File "/home/pi/.local/lib/python3.9/site-packages/picframe/start.py", line 8, in <module>
    from picframe import model, viewer_display, controller, __version__
  File "/home/pi/.local/lib/python3.9/site-packages/picframe/viewer_display.py", line 1, in <module>
    import pi3d
  File "/home/pi/.local/lib/python3.9/site-packages/pi3d/__init__.py", line 10, in <module>
    from pi3d.constants import (USE_PYGAME, PIL_OK,
  File "/home/pi/.local/lib/python3.9/site-packages/pi3d/constants/__init__.py", line 200, in <module>
    PLATFORM, bcm, openegl, opengles = _detect_platform_and_load_libraries()
  File "/home/pi/.local/lib/python3.9/site-packages/pi3d/constants/__init__.py", line 195, in _detect_platform_and_load_libraries
    set_gles_function_args(opengles) #function defined in constants/gl.py
  File "/home/pi/.local/lib/python3.9/site-packages/pi3d/constants/gl.py", line 387, in set_gles_function_args
    gles.glActiveTexture.argtypes = [GLenum] #
`

I guess, that's because I didn't install the right driver in raspi config. But which one do I choose?

**Comment by sapnho** [comment]
I'll have to write a completely revised version for Bullseye once I get it to work.

**Comment by sapnho** [comment]
> I use bullseye.
> 
> Is there a reason why you try buster?

Yes, the whole batch of problems we saw back then: https://github.com/helgeerbe/picframe/issues/195

I never got around to installing a running version with Bullseye with the same performance as Buster. But it seems you have found a way. How did you get it to work on a Pi 4?

**Comment by sapnho** [comment]
> What happens if you try `pip install picframe==2024.5.31`

> pip install picframe==2024.5.31
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting picframe==2024.5.31
  Could not find a version that satisfies the requirement picframe==2024.5.31 (from versions: 0.1.1, 0.1.3, 0.1.5, 0.1.6, 0.1.9, 2021.2.27a1, 2021.2.27a2, 2021.2.27a3, 2021.2.27a4, 2021.2.27a5, 2021.2.27a6, 2021.3.10, 2021.3.20, 2021.4.2, 2021.5.2, 2021.5.5, 2021.6.26, 2021.7.5, 2021.8.30, 2021.9.22, 2021.10.6, 2021.11.4, 2022.1.20, 2022.1.20.post1, 2022.3.24, 2022.4.19, 2022.6.3, 2022.12.4, 2022.12.13)
No matching distribution found for picframe==2024.5.31

**Comment by sapnho** [comment]
> I also updated the blueprint https://gist.github.com/helgeerbe/78f66ecf1f5206ce50ef9599892f202a .
> 
> On bullesye everythings works fine for me.

Great, thanks. I can't find your Wiki page where you originally described the integration, and mine is a bit outdated. Would you have the link again, please @helgeerbe ?

**Comment by helgeerbe** [comment]
https://github.com/helgeerbe/picframe/wiki/Homeassistant

**Comment by sapnho** [comment]
Thanks! I only now discovered the Wiki button on the right, I had always looked left... Everything works fine with Bookworm, will write a revised setup version shortly.

The only thing left is the Home Assistant integration with the filters. I replaced the old blueprint with the new one. However, I was wondering, what else needs to be changed in HA? So much has changed in HA since you first developed the integration and I am not sure if the Wiki page reflects this.

**Comment by sapnho** [comment]
Thanks. I am a bit lost with the Home Assistant Update.

I replaced the Blueprint, removed the MQTT integration, which came back after restarting picframe and removed the helpers you specified. Everything works fine except for the text inputs, which don't work. Tags, Location, Dates. When I enter a tag, I can see the message sent via MQTT (in MQTT Explorer) but the image choice is not adapted. I went through the original installation but I am not sure where I missed something.

**Comment by sapnho** [comment]
![Uploading Screenshot 2024-06-02 at 19.45.40.png…]()

**Comment by sapnho** [comment]
![Screenshot 2024-06-02 at 19 45 40](https://github.com/helgeerbe/picframe/assets/33040431/c7b2871e-5052-4070-a01c-957ad16cbd0d)

**Comment by helgeerbe** [comment]
can you check in the blueprint the entity ids of your helpers. If you deleted the original ones, they may have a different name.
![image](https://github.com/helgeerbe/picframe/assets/59169507/ab5b1a91-4047-4480-aa0a-0d006330a361)

**Comment by sapnho** [comment]
Hmm, not entirely sure what you mean, but the names are the same everywhere.
![Screenshot 2024-06-02 at 21 26 43](https://github.com/helgeerbe/picframe/assets/33040431/266de359-d6d9-4339-ae04-5c0edd551961)
![Screenshot 2024-06-02 at 21 28 42](https://github.com/helgeerbe/picframe/assets/33040431/b7137296-d87e-4010-b1ce-cfa75bed323d)

**Comment by helgeerbe** [comment]
can you show me the topic, where the tags input is send from the mqtt explorer?

**Comment by helgeerbe** [comment]
if you enter a tag in the web frontend of picframe, does it show up in home assistant?

**Comment by sapnho** [comment]
> can you show me the topic, where the tags input is send from the mqtt explorer?

![Screenshot 2024-06-02 at 22 00 10](https://github.com/helgeerbe/picframe/assets/33040431/ba8601c9-4951-41d5-bf4b-632aaaf3298e)
I entered "Bike" as a tag.

**Comment by sapnho** [comment]
> if you enter a tag in the web frontend of picframe, does it show up in home assistant?

Hmm, not using this so far. I have activated it now in configuration.yaml but can't access it with http://192.168.178.67/home/pi/picframe_data/html:9000

But I wonder if that is the correct address?

**Comment by sapnho** [comment]
![Screenshot 2024-06-02 at 22 13 58](https://github.com/helgeerbe/picframe/assets/33040431/55d8f201-abc6-4b60-8e06-f9bdd6dce68f)

**Comment by helgeerbe** [comment]
http://192.168.178.67:9000

**Comment by sapnho** [comment]
> > if you enter a tag in the web frontend of picframe, does it show up in home assistant?

Yes, it does.. but I can't remove it then. I can delete the Tags entry but the number of selected images stays the same.

**Comment by helgeerbe** [comment]
What I don't understand that you have a topic cmd under picframe_tags_filter. I would expect the response in picframe/tags_filter

![image](https://github.com/helgeerbe/picframe/assets/59169507/5c501b32-ac98-43fb-a4c5-39bfbeb8638c)


Can you send me the content of `picframe_input_text.yaml` Your will find it under `blueprints/automation/helgeerbe` starting from the directory where your `configuration.yaml` from home assistant is located.

**Comment by sapnho** [comment]
Done. And one more observation: When I delete the tag filter value, and refresh HA, it comes back.

**Comment by helgeerbe** [comment]
OK, found it.

I bet you didn't added in your Home Assistant UI not the helper `input_text.picframe_tags_filter` instead you added the mqtt element ` text.picframe_tags_filter'

Can you confirm that?

I wasn't aware that the ui element is created automatically. That might simplify the blueprint in the future.

**Comment by sapnho** [comment]
> I wasn't aware that the ui element is created automatically. That might simplify the blueprint in the future.

Yes, they are all created automatically. Most convenient.

> I bet you didn't added in your Home Assistant UI not the helper input_text.picframe_tags_filter instead you added the mqtt element ` text.picframe_tags_filter'

I am not sure what you mean. These are my helpers:
![Tags](https://github.com/helgeerbe/picframe/assets/33040431/55b493d2-9c8b-40c8-b72c-83b816c5405f)

**Comment by helgeerbe** [comment]
![image](https://github.com/helgeerbe/picframe/assets/59169507/b3fc4351-9f8b-4fb7-b6e5-a385f3b89c97)
Use the yellow, not the red element

**Comment by sapnho** [comment]
And in the Frontend, I installed
![Front](https://github.com/helgeerbe/picframe/assets/33040431/da47f1df-0a32-4538-b40f-c7bfecc7fcac)

**Comment by sapnho** [comment]
But when I add values there, no filtering is applied.

**Comment by helgeerbe** [comment]
your mqtt message says you are using `text.picframe_tags_filter`, the tag "Bike" is in the `cmd` element.

your entity card says you are using `input_text.picframe_tags_filter`

Now I'm confused.

Can you ad both elements into your entity card and check the mqtt messages.

**Comment by sapnho** [comment]
Oh my, my update seems to have messed everything up! :-))
So, the MQTT integration gives this:
![Test](https://github.com/helgeerbe/picframe/assets/33040431/4a42fc38-f11e-405b-89f0-7f4152e2f7ae)

**Comment by sapnho** [comment]
The Text Input card doesn't appear in MQTT Explorer-
I cannot see this entry of yours:
![Screenshot 2024-06-03 at 21 07 52](https://github.com/helgeerbe/picframe/assets/33040431/6c50e117-3bdb-4b18-95cb-23ea9179bcc5)

**Comment by helgeerbe** [comment]
looks like the automation didn't run. Have you restarted home assistant aber configuring the blueprint?

**Comment by sapnho** [comment]
Yes, I had but just in case, I just did a full restart of the HA system. This is how it looks:
![Screenshot 2024-06-03 at 21 24 40](https://github.com/helgeerbe/picframe/assets/33040431/008cb375-f0ca-45d0-91c6-edd29101008c)

**Comment by helgeerbe** [comment]
Is the automation triggered, when you enter a tag?

Can you show the traces?

![image](https://github.com/helgeerbe/picframe/assets/59169507/a6cc503a-99c0-4ab0-b57b-1451fd1f1fbb)

**Comment by sapnho** [comment]
Can you tell me exactly what to do so that I can show you this result? Never worked with traces before.

**Comment by sapnho** [comment]
The thing is, I don't see any automation called "picframe".

**Comment by sapnho** [comment]
And when I do "show automations" under your Blueprint, I don't see any.

**Comment by sapnho** [comment]
I guess, it's time to update this great article: https://www.thedigitalpictureframe.com/integrate-raspberry-pi-picture-frame-home-assistant/

Should be a lot shorter because HA creates the front end automatically.

**Comment by helgeerbe** [comment]
Just to be sure. Did you create the automation from the blueprint?

![Einstellungen_–_Home_Assistant](https://github.com/helgeerbe/picframe/assets/59169507/fb9162cb-0ff2-4d27-a724-3517830dc498)

**Comment by sapnho** [comment]
Ah, a very good question: No, I hadn't! :.-)

Now, the tags and country filters work fine! 

The date filters reduce the number of selected photos but not the right date range...

**Comment by sapnho** [comment]
Can Blueprints also create Helpers? This would make the instructions for users even easier.

**Comment by helgeerbe** [comment]
Good to hear, that it was at the end an easy solution.

What do you mean about the right date range? Can you show what you entered and how the mqqt payload looks like? The automation converts the entered text, into a timestamp number.

> Can Blueprints also create Helpers? This would make the instructions for users even easier.

Unfortunately not. For `tags` and `location` we could get rid of the helpers, because the input text field elements are now created by mqtt discovery. Problem would be the date fields. The automation takes a text like dd.mm.yyyy and converts ist into a timestamp number.  I see 2 possible solution. 1. It might be possible to manipulate the text of the date input field before it's published over mqtt. 2. We extend picframe and convert the date text there into the timestamp. Advantage of the 2nd solution, we wouldn't need blueprint and automation anymore. Disadvatange performance depends on a full communication cyle, because every input has to be processed not in the webfrontend but on the picframe server.

**Comment by sapnho** [comment]
Date from 01.01.2024 gives
![Screenshot 2024-06-04 at 11 06 24](https://github.com/helgeerbe/picframe/assets/33040431/b7107a30-356b-4d1f-bfb7-665bb9ee5963)

**Comment by helgeerbe** [comment]
Convertion seems to be correct: 
- 01.01.2023 -> 1704063600 -> Mon Jan 01 2024 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)
- 31.12.2023 -> 1703977200 -> Sun Dec 31 2023 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)

Problematic could be that images might be included in the start date, but excluded from the end date.

**Comment by sapnho** [comment]
Which I do would do where?

**Comment by helgeerbe** [comment]
I just updated the blueprint. `date_from`starts at midnight, `date_to` ends at 23:59:59

**Comment by helgeerbe** [comment]
If this works for you, can you close this issue pleas.

**Comment by sapnho** [comment]
> I just updated the blueprint. `date_from`starts at midnight, `date_to` ends at 23:59:59

What's the best way to update the blueprint? Should I delete the automation first?

**Comment by helgeerbe** [comment]
Havn't tested it, but I would try this:
1. Update blueprint
2. reload automations
![Screenshot_05_06_24__12_14](https://github.com/helgeerbe/picframe/assets/59169507/8b0f5466-d0ed-4eb3-874a-64ceb18218d8)

If this is not working, you have to delete the automation, and have to recreated it from the blueprint. But my assumption is, that the above describted workflow will work. Let me know.

**Comment by sapnho** [comment]
Ok, I did that, thanks. The funny thing is that Date To works, but date from is still flawed. 

However, Date to doesn't revert to the default value (year 2038) when you delete the entry.

**Comment by sapnho** [comment]
When I enter 01.01.2024 in Date From, this is sent via MQTT:
![Screenshot 2024-06-05 at 12 31 45](https://github.com/helgeerbe/picframe/assets/33040431/6ca4c8d5-0765-4ed6-b94d-1020e21624db)

Does that information help in any way?

**Comment by sapnho** [comment]
Or a full filtering:
![Screenshot 2024-06-05 at 12 35 37](https://github.com/helgeerbe/picframe/assets/33040431/733c7ce9-921d-4e15-8fca-d2b9a9a4e0ca)
![Screenshot 2024-06-05 at 12 35 33](https://github.com/helgeerbe/picframe/assets/33040431/035e619b-c351-4ef8-bb91-ddc069ab186a)

**Comment by sapnho** [comment]
Ok, will try that.

> This works for me on Safari and Chrome. Have in mind after deleting you have to press enter, or click into an other ui element. So the input is processed.

I did. Maybe something else I should have installed is missing?

**Comment by sapnho** [comment]
@helgeerbe What would I have to remove to completely start from scratch the Home Assistant integration? I'd like to go through the steps that somebody installing the system for the first time encounters after all your great updates.

**Comment by helgeerbe** [comment]
I see the issue on the home assistant app for date_to. The last entered date is restored, when you delete the input. Date_from works.Have to investigate further.

Removing everything
- delete automation
- delete blueprint
- delete helpers
- delete Mqtt device picframe

**Comment by sapnho** [comment]
Thanks. I'll wait for you to solve this last issue and will then do a clean install.

**Comment by helgeerbe** [comment]
@sapnho can you test the latest blueprint, please

**Comment by sapnho** [comment]
Works beautifully, thanks much!
